Controllers/NotificationWidgetController.cs
using Orchard;
using Orchard.ContentManagement;
using Orchard.Localization;
using Orchard.Logging;
using RealtyShares.UserNotifications.Models;
using System.Web.Mvc;
using System.Linq;

namespace RealtyShares.UserNotifications.Controllers
{
    public class NotificationWidgetController : Controller
    {
        private readonly IContentManager _contentManager;
        private readonly IWorkContextAccessor _wca;
        

        public Localizer T { get; set; }

        public ILogger Logger { get; set; }


        public NotificationWidgetController(IContentManager contentManager, IWorkContextAccessor wca)
        {
            _contentManager = contentManager;
            _wca = wca;

            T = NullLocalizer.Instance;
            Logger = NullLogger.Instance;
        }


        [HttpPost]
        public bool RemoveNotification(int id)
        {
            if (_wca.GetContext().CurrentUser == null)
            {
                return false;
            }

            // Commented out for testing purposes.
            var notificationUserPart = _wca.GetContext().CurrentUser.As<NotificationsUserPart>();

            var entryCollection = notificationUserPart.RecentNotificationEntries;
            var relevantNotificationEntry = entryCollection.FirstOrDefault(entry => entry.NotificationId == id);

            if (relevantNotificationEntry == null)
            {
                return false;
            }

            relevantNotificationEntry.IsRead = true;

            notificationUserPart.RecentNotificationEntries = entryCollection;

            return true;
        }
    }
}

Views/Parts.NotificationWidget.cshtml
@using Orchard.ContentManagement;
@using RealtyShares.UserNotifications.Models;

@{
    Script.Require("jQuery");
    
    
    Style.Require("RealtyShares.UserNotifications.NotificationWidget");
    
    
    var notifications = Model.ContentPart.UnreadNotifications as IList<INotification>;
    var removeLink = Url.Action("RemoveNotification", "NotificationWidget", new { Area = "RealtyShares.UserNotifications" });
}

@foreach (var notification in notifications)
{
    <div class="realtyshares-usernotifications-notificationwidget-notification">
        <div class="realtyshares-usernotifications-notificationwidget-remove" data-id="@notification.Id"></div>
        <div class="realtyshares-usernotifications-notificationwidget-title">@notification.Title</div>
        <div class="realtyshares-usernotifications-notificationwidget-body">@Html.Raw(notification.Body)</div>
    </div>
}


@using (Script.Foot())
{
    <script type="text/javascript">
        (function ($) {
            $(function () {
                $('.realtyshares-usernotifications-notificationwidget-remove').click(function () {
                    var notificationId = $(this).attr('data-id');
                    var parentElement = $(this).parent();
                    var requestVerificationToken = '@Html.AntiForgeryTokenValueOrchard()';

                    $.post("@removeLink", { __RequestVerificationToken: requestVerificationToken, id: notificationId })
                    .done(function (successValue) {
                        var success = successValue === "True";

                        if (success) {
                            parentElement.remove();
                        } else {
                            alert('@T("Remove notification failed to remove.")');
                        }
                    })
                    .fail(function () {
                        alert('@T("Remove notification failed to remove because of server error.")');
                    })
                })
            });
        })(jQuery);
    </script>
}

Views/RealtyShares.Content.PublishButton.cshtml
@using Orchard.ContentManagement;
@using Orchard.Core.Contents;
@using Orchard.Utility.Extensions;

@if (Authorizer.Authorize(Permissions.PublishContent, (IContent)Model.ContentItem)) {
<fieldset class="publish-button">
    <button type="submit" name="submit.Publish" value="submit.Publish">@T("Send Now")</button>
</fieldset>
}

Views/RealtyShares.Parts.Common.Body.Tokenized.cshtml
@{
    var bodyPart = (Model.Model as Orchard.Core.Common.ViewModels.BodyEditorViewModel).BodyPart;
    var prefix = Model.Metadata.Prefix as string;
    var textFieldName = String.Format("{0}.Text", prefix);
    var textFieldId = String.Format("{0}_Text", prefix);
}

<fieldset>
    <label for="@textFieldId">@T("Notification Text")</label>
    @Html.TextArea(textFieldName, bodyPart.Text, new { @class = "text large tokenized" })
    @Html.ValidationMessage(textFieldName)
</fieldset>

@Display.TokenHint()

Views/RealtyShares.Parts.PublishLater.cshtml
@using Orchard.ContentManagement;
@using Orchard.Core.Contents;
@using Orchard.Utility.Extensions;

@{
    Style.Require("PublishLater_DatePicker");

    var publishLaterViewModel = Model.Model as Orchard.PublishLater.ViewModels.PublishLaterViewModel;
    var prefix = Model.Metadata.Prefix as string;
    var scheduledPublishDateFieldName = String.Format("{0}.ScheduledPublishDate", prefix);
    var scheduledPublishTimeFieldName = String.Format("{0}.ScheduledPublishTime", prefix);
    var scheduledPublishDateFieldId = String.Format("{0}_ScheduledPublishDate", prefix);
    var scheduledPublishTimeFieldId = String.Format("{0}_ScheduledPublishTime", prefix);
}

@if (Authorizer.Authorize(Permissions.PublishContent, Model.Model.ContentItem)) {
    
<fieldset class="publish-later-datetime">
    <legend>@T("Send")</legend>
    <label class="forpicker" for="@scheduledPublishDateFieldId">@T("Date")</label>
    @Html.TextBox(scheduledPublishDateFieldName, publishLaterViewModel.ScheduledPublishDate)
    
    <label class="forpicker" for="@scheduledPublishTimeFieldId">@T("Time")</label>
    @Html.TextBox(scheduledPublishTimeFieldName, publishLaterViewModel.ScheduledPublishTime)
	<button type="submit" name="submit.Save" value="submit.PublishLater">@T("Send Later")</button>
</fieldset>

using (Script.Foot()) {

    @* generates the localization script *@
    @Display(New.DatePickerLocalization())
    @Display(New.TimePickerLocalization())

<script type="text/javascript">
//<![CDATA[
    $(function () {
        
        var clearHint = function ($this) { if ($this.val() == $this.data("hint")) { $this.removeClass("hinted").val("") } };
        var resetHint = function ($this) { setTimeout(function () { if (!$this.val()) { $this.addClass("hinted").val($this.data("hint")) } }, 300) };
        @* todo: (heskew) make a plugin *@
        $("label.forpicker").each(function () {
            var $this = $(this);
            var pickerInput = $("#" + $this.attr("for"));
            if (!pickerInput.val()) {
                pickerInput.data("hint", $this.text());
                pickerInput.addClass("hinted")
                    .val(pickerInput.data("hint"))
                    .focus(function() {clearHint($(this));})
                    .blur(function() {resetHint($(this));});
                $this.closest("form").submit(function() {clearHint(pickerInput); pickerInput = 0;});
            }
        });
        
        $('#@scheduledPublishDateFieldId').datepicker({ showAnim: "" }).focus(function () { $('#@ViewData.TemplateInfo.GetFullHtmlFieldId("Command_PublishLater")').attr("checked", "checked") });
        $('#@scheduledPublishTimeFieldId').timepicker({ stepMinute: 5 }).focus(function () { $('#@ViewData.TemplateInfo.GetFullHtmlFieldId("Command_PublishLater")').attr("checked", "checked") });
    })
//]]>
</script>
}

}

Views/RealtyShares.Parts.Title.Tokenized.cshtml
@{
    var titlePart = Model.Model as Orchard.Core.Title.Models.TitlePart;
    var prefix = Model.Metadata.Prefix as string;
    var titleFieldName = String.Format("{0}.Title", prefix);
    var titleFieldId = String.Format("{0}_Title", prefix);
}

<fieldset>
    <label for="@titleFieldId">@T("Title")</label>
    @Html.TextBox(titleFieldName, titlePart.Title, new { @class = "text large tokenized", autofocus = "autofocus" })
    <span class="hint">@T("You must provide a title for this content item")</span>
</fieldset>

@Display.TokenHint()

Views/UserNotifications.Content.PublishButton.cshtml
@using Orchard.ContentManagement;
@using Orchard.Core.Contents;
@using Orchard.Utility.Extensions;

@if (Authorizer.Authorize(Permissions.PublishContent, (IContent)Model.ContentItem)) {
<fieldset class="publish-button">
    <button type="submit" name="submit.Publish" value="submit.Publish">@T("Send Now")</button>
</fieldset>
}

Views/UserNotifications.Parts.Common.Body.Tokenized.cshtml
@{
    var bodyPart = (Model.Model as Orchard.Core.Common.ViewModels.BodyEditorViewModel).BodyPart;
    var prefix = Model.Metadata.Prefix as string;
    var textFieldName = String.Format("{0}.Text", prefix);
    var textFieldId = String.Format("{0}_Text", prefix);
}

<fieldset>
    <label for="@textFieldId">@T("Notification Text")</label>
    @Html.TextArea(textFieldName, bodyPart.Text, new { @class = "text large tokenized" })
    @Html.ValidationMessage(textFieldName)
</fieldset>

@Display.TokenHint()

Views/UserNotifications.Parts.PublishLater.cshtml
@using Orchard.ContentManagement;
@using Orchard.Core.Contents;
@using Orchard.Utility.Extensions;

@{
    Style.Require("PublishLater_DatePicker");

    var publishLaterViewModel = Model.Model as Orchard.PublishLater.ViewModels.PublishLaterViewModel;
    var prefix = Model.Metadata.Prefix as string;
    var scheduledPublishDateFieldName = String.Format("{0}.ScheduledPublishDate", prefix);
    var scheduledPublishTimeFieldName = String.Format("{0}.ScheduledPublishTime", prefix);
    var scheduledPublishDateFieldId = String.Format("{0}_ScheduledPublishDate", prefix);
    var scheduledPublishTimeFieldId = String.Format("{0}_ScheduledPublishTime", prefix);
}

@if (Authorizer.Authorize(Permissions.PublishContent, Model.Model.ContentItem)) {
    
<fieldset class="publish-later-datetime">
    <legend>@T("Send")</legend>
    <label class="forpicker" for="@scheduledPublishDateFieldId">@T("Date")</label>
    @Html.TextBox(scheduledPublishDateFieldName, publishLaterViewModel.ScheduledPublishDate)
    
    <label class="forpicker" for="@scheduledPublishTimeFieldId">@T("Time")</label>
    @Html.TextBox(scheduledPublishTimeFieldName, publishLaterViewModel.ScheduledPublishTime)
	<button type="submit" name="submit.Save" value="submit.PublishLater">@T("Send Later")</button>
</fieldset>

using (Script.Foot()) {

    @* generates the localization script *@
    @Display(New.DatePickerLocalization())
    @Display(New.TimePickerLocalization())

<script type="text/javascript">
//<![CDATA[
    $(function () {
        
        var clearHint = function ($this) { if ($this.val() == $this.data("hint")) { $this.removeClass("hinted").val("") } };
        var resetHint = function ($this) { setTimeout(function () { if (!$this.val()) { $this.addClass("hinted").val($this.data("hint")) } }, 300) };
        @* todo: (heskew) make a plugin *@
        $("label.forpicker").each(function () {
            var $this = $(this);
            var pickerInput = $("#" + $this.attr("for"));
            if (!pickerInput.val()) {
                pickerInput.data("hint", $this.text());
                pickerInput.addClass("hinted")
                    .val(pickerInput.data("hint"))
                    .focus(function() {clearHint($(this));})
                    .blur(function() {resetHint($(this));});
                $this.closest("form").submit(function() {clearHint(pickerInput); pickerInput = 0;});
            }
        });
        
        $('#@scheduledPublishDateFieldId').datepicker({ showAnim: "" }).focus(function () { $('#@ViewData.TemplateInfo.GetFullHtmlFieldId("Command_PublishLater")').attr("checked", "checked") });
        $('#@scheduledPublishTimeFieldId').timepicker({ stepMinute: 5 }).focus(function () { $('#@ViewData.TemplateInfo.GetFullHtmlFieldId("Command_PublishLater")').attr("checked", "checked") });
    })
//]]>
</script>
}

}

Views/UserNotifications.Parts.Title.Tokenized.cshtml
@{
    var titlePart = Model.Model as Orchard.Core.Title.Models.TitlePart;
    var prefix = Model.Metadata.Prefix as string;
    var titleFieldName = String.Format("{0}.Title", prefix);
    var titleFieldId = String.Format("{0}_Title", prefix);
}

<fieldset>
    <label for="@titleFieldId">@T("Title")</label>
    @Html.TextBox(titleFieldName, titlePart.Title, new { @class = "text large tokenized", autofocus = "autofocus" })
    @Html.Hint(T("You must provide a title for this content item"))
</fieldset>

@Display.TokenHint()